//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baocaovuonquocgia.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tongcuclamnghiepEntities : DbContext
    {
        public tongcuclamnghiepEntities()
            : base("name=tongcuclamnghiepEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<m_account> m_account { get; set; }
        public DbSet<m_component> m_component { get; set; }
        public DbSet<m_controller> m_controller { get; set; }
        public DbSet<m_controller_role> m_controller_role { get; set; }
        public DbSet<m_header> m_header { get; set; }
        public DbSet<m_precious> m_precious { get; set; }
        public DbSet<m_reporttable> m_reporttable { get; set; }
        public DbSet<m_role> m_role { get; set; }
        public DbSet<m_unit> m_unit { get; set; }
        public DbSet<m_unit_datareport> m_unit_datareport { get; set; }
        public DbSet<m_unit_datereport_autorows> m_unit_datereport_autorows { get; set; }
        public DbSet<m_unit_precious> m_unit_precious { get; set; }
        public DbSet<m_unitversion> m_unitversion { get; set; }
    }
}
