//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baocaovuonquocgia.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_account
    {
        public m_account()
        {
            this.m_precious = new HashSet<m_precious>();
            this.m_unit = new HashSet<m_unit>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string fullname { get; set; }
        public Nullable<bool> gender { get; set; }
        public string email { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
    
        public virtual m_role m_role { get; set; }
        public virtual ICollection<m_precious> m_precious { get; set; }
        public virtual ICollection<m_unit> m_unit { get; set; }
    }
}
