//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baocaovuonquocgia.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_controller
    {
        public m_controller()
        {
            this.m_controller_role = new HashSet<m_controller_role>();
        }
    
        public int id { get; set; }
        public string controllername { get; set; }
        public string controllerurl { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<int> level { get; set; }
        public Nullable<bool> status { get; set; }
        public string controllerdisplay { get; set; }
        public Nullable<int> controller_id { get; set; }
    
        public virtual ICollection<m_controller_role> m_controller_role { get; set; }
    }
}
