//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baocaovuonquocgia.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_component
    {
        public m_component()
        {
            this.m_unit_datareport = new HashSet<m_unit_datareport>();
        }
    
        public int id { get; set; }
        public string componentname { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> orderrow { get; set; }
        public Nullable<int> header_id { get; set; }
        public Nullable<int> reporttable_id { get; set; }
        public Nullable<int> typevalue { get; set; }
    
        public virtual m_header m_header { get; set; }
        public virtual m_reporttable m_reporttable { get; set; }
        public virtual ICollection<m_unit_datareport> m_unit_datareport { get; set; }
    }
}
