//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baocaovuonquocgia.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_header
    {
        public m_header()
        {
            this.m_component = new HashSet<m_component>();
            this.m_unit_datereport_autorows = new HashSet<m_unit_datereport_autorows>();
        }
    
        public int id { get; set; }
        public string headername { get; set; }
        public Nullable<int> colspan { get; set; }
        public Nullable<int> rowspan { get; set; }
        public Nullable<int> level { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<int> reporttable_id { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> header_id { get; set; }
        public Nullable<bool> is_bold { get; set; }
        public Nullable<bool> is_upper { get; set; }
        public Nullable<bool> is_valuebold { get; set; }
        public Nullable<bool> is_valueupper { get; set; }
        public string valuetextalign { get; set; }
        public Nullable<bool> is_no { get; set; }
        public Nullable<bool> is_component { get; set; }
    
        public virtual ICollection<m_component> m_component { get; set; }
        public virtual m_reporttable m_reporttable { get; set; }
        public virtual ICollection<m_unit_datereport_autorows> m_unit_datereport_autorows { get; set; }
    }
}
