//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baocaovuonquocgia.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_precious
    {
        public m_precious()
        {
            this.m_unit_precious = new HashSet<m_unit_precious>();
        }
    
        public int id { get; set; }
        public string precious_name { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> completedate { get; set; }
        public Nullable<int> account_id { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> slowday { get; set; }
    
        public virtual m_account m_account { get; set; }
        public virtual ICollection<m_unit_precious> m_unit_precious { get; set; }
    }
}
