//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baocaovuonquocgia.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_reporttable
    {
        public m_reporttable()
        {
            this.m_component = new HashSet<m_component>();
            this.m_header = new HashSet<m_header>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> showtotal { get; set; }
        public Nullable<bool> autorow { get; set; }
    
        public virtual ICollection<m_component> m_component { get; set; }
        public virtual ICollection<m_header> m_header { get; set; }
    }
}
