//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baocaovuonquocgia.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_unit_datareport
    {
        public int id { get; set; }
        public Nullable<int> unit_precious_id { get; set; }
        public Nullable<int> component_id { get; set; }
        public string data_text { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> editlasttime { get; set; }
    
        public virtual m_component m_component { get; set; }
        public virtual m_unit_precious m_unit_precious { get; set; }
    }
}
