//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baocaovuonquocgia.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_unit_datereport_autorows
    {
        public int id { get; set; }
        public Nullable<int> orderrow { get; set; }
        public string datatext { get; set; }
        public Nullable<int> header_id { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> editdate { get; set; }
        public Nullable<int> unit_precious_id { get; set; }
        public Nullable<int> reporttable_id { get; set; }
    
        public virtual m_header m_header { get; set; }
        public virtual m_unit_precious m_unit_precious { get; set; }
    }
}
