//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baocaovuonquocgia.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_unit
    {
        public m_unit()
        {
            this.m_unit_precious = new HashSet<m_unit_precious>();
            this.m_unitversion = new HashSet<m_unitversion>();
        }
    
        public int id { get; set; }
        public string unitname { get; set; }
        public string address { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> account_id { get; set; }
        public Nullable<double> ngansachnhannuoc1 { get; set; }
        public Nullable<double> ngansachnhanuoc2 { get; set; }
        public Nullable<int> tongcanbo1 { get; set; }
        public Nullable<int> tongcanbo2 { get; set; }
        public Nullable<double> dientich1 { get; set; }
        public Nullable<double> dientich2 { get; set; }
        public string ngaythanhlap { get; set; }
    
        public virtual m_account m_account { get; set; }
        public virtual ICollection<m_unit_precious> m_unit_precious { get; set; }
        public virtual ICollection<m_unitversion> m_unitversion { get; set; }
    }
}
