//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baocaovuonquocgia.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_unit_precious
    {
        public m_unit_precious()
        {
            this.m_unit_datareport = new HashSet<m_unit_datareport>();
            this.m_unit_datereport_autorows = new HashSet<m_unit_datereport_autorows>();
        }
    
        public int id { get; set; }
        public Nullable<int> unit_id { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> completedate { get; set; }
        public Nullable<int> precious_id { get; set; }
    
        public virtual m_precious m_precious { get; set; }
        public virtual m_unit m_unit { get; set; }
        public virtual ICollection<m_unit_datareport> m_unit_datareport { get; set; }
        public virtual ICollection<m_unit_datereport_autorows> m_unit_datereport_autorows { get; set; }
    }
}
